executor: go-machine-medium
steps:
- checkout
- install-go
- install-protobuf
- run:
    name: "Check proto deltas"
    command: |
      make protobuild
      echo "Testing git diffs..."
      git diff --exit-code
      git status --porcelain
      test -z "$(git status --porcelain)"
- run:
    name: "Check API deltas"
    command: |
      make api
      echo "Testing git diffs..."
      git diff --exit-code
      git status --porcelain
      test -z "$(git status --porcelain)"