executor: go-machine-medium
steps:
- checkout
- install-go
- install-protobuf
- run:
    name: "Check proto deltas"
    command: |
      make protobuild
      git diff --exit-code
      git status --porcelain
      test -z $(git status --porcelain)
- run:
    name: "Check API deltas"
    command: |
      make api
      git diff --exit-code
      git status --porcelain
      test -z $(git status --porcelain)