---
description: >
  Ensure protobuf is installed
steps:
  - run:
      name: "Install protobuf"
      command: |
        VERSION="3.17.3"
        PB_REL="https://github.com/protocolbuffers/protobuf/releases"
        ARCH="$(uname -m)"

        PACKAGE_NAME=protoc-$VERSION-linux-$ARCH.zip
        curl -LO $PB_REL/download/v$VERSION/$PACKAGE_NAME
        unzip $PACKAGE_NAME -d $HOME/.locaL
        export PATH="$PATH:$HOME/.local/bin"

        BIN="$HOME/.local/bin"
        VERSION="0.56.0"
        BINARY_NAME="buf"
        BUF_PACKAGE="${BINARY_NAME}-$(uname -s)-$(uname -m)"
        curl -LO https://github.com/bufbuild/buf/releases/download/v${VERSION}/$BUF_PACKAGE
        echo "Downloaded buf package..."
        mv $BUF_PACKAGE ${BIN}/${BINARY_NAME}
        chmod +x "${BIN}/${BINARY_NAME}"